// Generated by dts-bundle-generator v9.5.1

export declare function health(): Promise<{
	status: string;
	timestamp: string;
	db: string;
}>;
export declare function createHOACheckout(input: {
	name: string;
	community: string;
	zip: string;
	units: number;
	contactName: string;
	contactEmail: string;
	contactPhone?: string;
	plan?: string;
}): Promise<{
	url: string | null;
	hoaId: string;
}>;
export declare function getHOAStats(): Promise<{
	totalHOAs: number;
	paidHOAs: number;
	totalUnits: number;
	arr: number;
}>;
export declare function getHOAList(): Promise<({
	_count: {
		violations: number;
		arcRequests: number;
		workOrders: number;
		meetings: number;
	};
	homeowners: {
		id: string;
		role: string;
	}[];
} & {
	id: string;
	contactName: string;
	zip: string;
	city: string;
	state: string;
	stripeSessionId: string | null;
	paid: boolean;
	paidAt: Date | null;
	createdAt: Date;
	name: string;
	community: string;
	units: number;
	contactEmail: string;
	contactPhone: string | null;
	amountCents: number | null;
	plan: string;
	pricePerUnit: number;
	onboardedAt: Date | null;
})[]>;
export declare function getHOA(id: string): Promise<({
	violations: {
		id: string;
		category: string;
		createdAt: Date;
		hoaId: string;
		address: string;
		homeownerId: string | null;
		aiAnalysis: string | null;
		aiAnalyzedAt: Date | null;
		updatedAt: Date;
		description: string;
		severity: string;
		status: string;
		photoUrls: string | null;
		reportedBy: string | null;
		noticeCount: number;
		latestNoticeAt: Date | null;
		nextNoticeAt: Date | null;
		fineCents: number | null;
		resolvedAt: Date | null;
		notes: string | null;
	}[];
	arcRequests: {
		id: string;
		hoaId: string;
		address: string;
		homeownerId: string;
		aiAnalysis: string | null;
		aiAnalyzedAt: Date | null;
		updatedAt: Date;
		description: string;
		status: string;
		projectType: string;
		estimatedCost: number | null;
		startDate: Date | null;
		documentUrls: string | null;
		reviewDeadline: Date;
		reviewedBy: string | null;
		reviewNotes: string | null;
		conditions: string | null;
		submittedAt: Date;
		decidedAt: Date | null;
	}[];
	workOrders: {
		id: string;
		category: string;
		createdAt: Date;
		hoaId: string;
		homeownerId: string | null;
		aiAnalysis: string | null;
		aiAnalyzedAt: Date | null;
		updatedAt: Date;
		description: string;
		status: string;
		photoUrls: string | null;
		notes: string | null;
		estimatedCost: number | null;
		title: string;
		area: string | null;
		location: string;
		priority: string;
		assignedTo: string | null;
		assignedAt: Date | null;
		actualCost: number | null;
		completionNotes: string | null;
		boardApproved: boolean;
		boardApprovedAt: Date | null;
		dueDate: Date | null;
		completedAt: Date | null;
	}[];
	homeowners: {
		id: string;
		email: string;
		phone: string | null;
		createdAt: Date;
		name: string;
		hoaId: string;
		address: string;
		unit: string | null;
		role: string;
		stripeCustomerId: string | null;
		moveInDate: Date | null;
		active: boolean;
	}[];
	meetings: {
		type: string;
		id: string;
		createdAt: Date;
		hoaId: string;
		aiAnalysis: string | null;
		aiAnalyzedAt: Date | null;
		updatedAt: Date;
		status: string;
		title: string;
		location: string | null;
		scheduledAt: Date;
		virtualLink: string | null;
		agenda: string | null;
		minutes: string | null;
		quorumRequired: number | null;
		quorumMet: boolean | null;
	}[];
	amenities: {
		id: string;
		createdAt: Date;
		name: string;
		hoaId: string;
		active: boolean;
		description: string | null;
		capacity: number | null;
		rules: string | null;
		depositCents: number | null;
		openTime: string | null;
		closeTime: string | null;
		advanceBookingDays: number | null;
	}[];
	announcements: {
		id: string;
		category: string;
		createdAt: Date;
		hoaId: string;
		aiAnalysis: string | null;
		aiAnalyzedAt: Date | null;
		title: string;
		body: string;
		pinned: boolean;
		sentEmail: boolean;
		sentAt: Date | null;
		authorName: string;
		expiresAt: Date | null;
	}[];
	budgets: {
		id: string;
		category: string;
		createdAt: Date;
		name: string;
		hoaId: string;
		notes: string | null;
		month: number | null;
		year: number;
		budgetedCents: number;
		actualCents: number;
	}[];
} & {
	id: string;
	contactName: string;
	zip: string;
	city: string;
	state: string;
	stripeSessionId: string | null;
	paid: boolean;
	paidAt: Date | null;
	createdAt: Date;
	name: string;
	community: string;
	units: number;
	contactEmail: string;
	contactPhone: string | null;
	amountCents: number | null;
	plan: string;
	pricePerUnit: number;
	onboardedAt: Date | null;
}) | null>;
export declare function createContractorCheckout(input: {
	company: string;
	contactName: string;
	email: string;
	phone?: string;
	category: string;
	zip: string;
}): Promise<{
	url: string | null;
	contractorId: string;
	position: number;
}>;
export declare function getContractorStats(): Promise<{
	total: number;
	paid: number;
	remaining: number;
	spotsLeft: number;
}>;
export declare function getWaitlistPosition(id: string): Promise<{
	id: string;
	company: string;
	contactName: string;
	email: string;
	phone: string | null;
	category: string;
	zip: string;
	city: string;
	state: string;
	stripeSessionId: string | null;
	paid: boolean;
	paidAt: Date | null;
	position: number | null;
	aiScreeningResult: string | null;
	aiScreenedAt: Date | null;
	createdAt: Date;
} | null>;
export declare function createContractorProfile(input: {
	waitlistId?: string;
	company: string;
	contactName: string;
	email: string;
	phone?: string;
	trades: string[];
	serviceZips: string[];
	licenseNumber?: string;
	insuranceStatus?: string;
	screeningStatus?: string;
	notes?: string;
}): Promise<{
	id: string;
	company: string;
	contactName: string;
	email: string;
	phone: string | null;
	createdAt: Date;
	updatedAt: Date;
	notes: string | null;
	waitlistId: string | null;
	trades: string;
	serviceZips: string;
	licenseNumber: string | null;
	insuranceStatus: string;
	screeningStatus: string;
}>;
export declare function promoteWaitlistToContractorProfile(input: {
	waitlistId: string;
	trades?: string[];
	serviceZips?: string[];
}): Promise<{
	id: string;
	company: string;
	contactName: string;
	email: string;
	phone: string | null;
	createdAt: Date;
	updatedAt: Date;
	notes: string | null;
	waitlistId: string | null;
	trades: string;
	serviceZips: string;
	licenseNumber: string | null;
	insuranceStatus: string;
	screeningStatus: string;
}>;
export declare function openContractorSlot(input: {
	hoaId: string;
	trade: string;
	capacity?: number;
	priceCents?: number;
	scarcityLabel?: string;
}): Promise<{
	id: string;
	createdAt: Date;
	hoaId: string;
	updatedAt: Date;
	status: string;
	capacity: number;
	trade: string;
	seatsTaken: number;
	priceCents: number;
	scarcityLabel: string | null;
}>;
export declare function grantContractorCommunityAccess(input: {
	contractorId: string;
	hoaId: string;
	trade: string;
	status?: string;
	accessType?: string;
}): Promise<{
	id: string;
	createdAt: Date;
	hoaId: string;
	updatedAt: Date;
	status: string;
	contractorId: string;
	trade: string;
	accessType: string;
	activeFrom: Date | null;
	activeUntil: Date | null;
}>;
export declare function createMarketplaceJobFromWorkOrder(input: {
	workOrderId: string;
	title?: string;
}): Promise<{
	id: string;
	category: string;
	createdAt: Date;
	hoaId: string;
	homeownerId: string | null;
	updatedAt: Date;
	description: string;
	status: string;
	title: string;
	workOrderId: string | null;
	arcRequestId: string | null;
	estimatedValueCents: number | null;
}>;
export declare function createMarketplaceJobFromARC(input: {
	arcRequestId: string;
	title?: string;
}): Promise<{
	id: string;
	category: string;
	createdAt: Date;
	hoaId: string;
	homeownerId: string | null;
	updatedAt: Date;
	description: string;
	status: string;
	title: string;
	workOrderId: string | null;
	arcRequestId: string | null;
	estimatedValueCents: number | null;
}>;
export declare function submitContractorQuote(input: {
	marketplaceJobId: string;
	contractorId: string;
	amountCents: number;
	scope: string;
}): Promise<{
	id: string;
	createdAt: Date;
	amountCents: number;
	updatedAt: Date;
	status: string;
	contractorId: string;
	marketplaceJobId: string;
	scope: string;
}>;
export declare function approveContractorQuote(input: {
	quoteId: string;
}): Promise<{
	marketplaceJob: {
		id: string;
		category: string;
		createdAt: Date;
		hoaId: string;
		homeownerId: string | null;
		updatedAt: Date;
		description: string;
		status: string;
		title: string;
		workOrderId: string | null;
		arcRequestId: string | null;
		estimatedValueCents: number | null;
	};
} & {
	id: string;
	createdAt: Date;
	amountCents: number;
	updatedAt: Date;
	status: string;
	contractorId: string;
	marketplaceJobId: string;
	scope: string;
}>;
export declare function recordMarketplaceTransaction(input: {
	jobId: string;
	quoteId?: string;
	contractorId: string;
	grossAmountCents: number;
	gatepassFeeCents: number;
	hoaShareCents: number;
	stripePaymentIntentId?: string;
	status?: string;
}): Promise<{
	id: string;
	createdAt: Date;
	hoaId: string;
	updatedAt: Date;
	status: string;
	contractorId: string;
	jobId: string;
	quoteId: string | null;
	grossAmountCents: number;
	gatepassFeeCents: number;
	hoaShareCents: number;
	stripePaymentIntentId: string | null;
}>;
export declare function recordCommunityRevenueShare(input: {
	hoaId: string;
	transactionId?: string;
	amountCents: number;
	type?: string;
	status?: string;
	appliedTo?: string;
	memo?: string;
}): Promise<{
	type: string;
	id: string;
	createdAt: Date;
	hoaId: string;
	amountCents: number;
	updatedAt: Date;
	status: string;
	transactionId: string | null;
	appliedTo: string | null;
	memo: string | null;
}>;
export declare function getMarketplaceDashboard(input: {
	hoaId: string;
	demo?: boolean;
}): Promise<{
	demo: boolean;
	slots: {
		id: string;
		trade: string;
		status: string;
		capacity: number;
		seatsTaken: number;
		priceCents: number;
		scarcityLabel: string;
	}[];
	jobs: {
		id: string;
		title: string;
		category: string;
		status: string;
		estimatedValueCents: number;
		source: string;
	}[];
	quotes: {
		id: string;
		contractor: string;
		amountCents: number;
		status: string;
		scope: string;
	}[];
	transactions: {
		id: string;
		grossAmountCents: number;
		gatepassFeeCents: number;
		hoaShareCents: number;
		status: string;
		contractor: string;
	}[];
	credits: {
		id: string;
		amountCents: number;
		status: string;
		memo: string;
	}[];
	complianceRecords: {
		id: string;
		summary: string;
		status: string;
	}[];
	proofLoop: {
		label: string;
		detail: string;
		value: string;
	}[];
} | {
	demo: boolean;
	slots: {
		id: string;
		createdAt: Date;
		hoaId: string;
		updatedAt: Date;
		status: string;
		capacity: number;
		trade: string;
		seatsTaken: number;
		priceCents: number;
		scarcityLabel: string | null;
	}[];
	jobs: {
		source: string;
		id: string;
		category: string;
		createdAt: Date;
		hoaId: string;
		homeownerId: string | null;
		updatedAt: Date;
		description: string;
		status: string;
		title: string;
		workOrderId: string | null;
		arcRequestId: string | null;
		estimatedValueCents: number | null;
	}[];
	quotes: {
		id: string;
		contractor: string;
		amountCents: number;
		status: string;
		scope: string;
	}[];
	transactions: {
		id: string;
		grossAmountCents: number;
		gatepassFeeCents: number;
		hoaShareCents: number;
		status: string;
		contractor: string;
	}[];
	credits: {
		id: string;
		amountCents: number;
		status: string;
		memo: string;
	}[];
	complianceRecords: {
		id: string;
		createdAt: Date;
		hoaId: string;
		status: string;
		contractorId: string;
		marketplaceJobId: string | null;
		complianceEventId: string | null;
		summary: string;
	}[];
	proofLoop: {
		label: string;
		detail: string;
		value: string;
	}[];
}>;
export declare function getInvestorProofMetrics(input: {
	hoaId: string;
	demo?: boolean;
}): Promise<{
	demo: boolean;
	headline: string;
	metrics: {
		hoaPipeline: number;
		transitionCases: number;
		privateMoatSignals: number;
		contractorSlotsOpen: number;
		contractorSignups: number;
		marketplaceJobs: number;
		quotesSubmitted: number;
		complianceRecords: number;
	};
	money: {
		demoGmvCents: number;
		gatepassFeeCents: number;
		hoaCreditsCents: number;
	};
	checklist: ({
		label: string;
		status: "done";
	} | {
		label: string;
		status: "demo";
	} | {
		label: string;
		status: "missing";
	})[];
	proofLinks: {
		label: string;
		href: string;
		note: string;
	}[];
	caution: string[];
}>;
export declare function getAustinPermits(zip?: string): Promise<{
	id: string;
	type: string;
	description: string;
	address: string;
	zip: string;
	contractor: string;
	contractorTrade: string | null;
	contractorPhone: string | null;
	value: string | null;
	date: string | null;
	status: string;
	projectId: string | null;
	permitClass: string | null;
	latitude: string | null;
	longitude: string | null;
}[]>;
export declare function getZoningCases(input?: {
	councilDistrict?: string;
	limit?: number;
}): Promise<{
	id: string;
	caseNumber: string;
	caseName: string;
	caseType: string;
	workType: string;
	status: string;
	proposedZoning: string | null;
	existingZoning: string | null;
	proposedLandUse: string | null;
	existingLandUse: string | null;
	siteAddress: string;
	councilDistrict: string | null;
	applicationDate: string | null;
	statusDate: string | null;
	ownerName: string | null;
	caseManager: string | null;
	isResidentialImpact: boolean;
}[]>;
export declare function getZoningByAddress(input: {
	streetName: string;
}): Promise<{
	streetName: string;
	zoningType: string;
	baseZone: string;
	baseZoneCategory: string;
}[]>;
export declare function getPermitApplications(input?: {
	zip?: string;
	limit?: number;
}): Promise<{
	id: string;
	type: string;
	description: string;
	address: string;
	zip: string;
	applicant: string;
	contractor: string | null;
	value: string | null;
	appliedDate: string | null;
	status: string;
	permitClass: string | null;
}[]>;
export declare function getLiveCityFeeds(input?: {
	zip?: string;
	councilDistrict?: string;
}): Promise<{
	permits: {
		id: string;
		type: string;
		description: string;
		address: string;
		zip: string;
		contractor: string;
		contractorTrade: string | null;
		contractorPhone: string | null;
		value: string | null;
		date: string | null;
		status: string;
		projectId: string | null;
		permitClass: string | null;
		latitude: string | null;
		longitude: string | null;
	}[];
	zoningCases: {
		id: string;
		caseNumber: string;
		caseName: string;
		caseType: string;
		workType: string;
		status: string;
		proposedZoning: string | null;
		existingZoning: string | null;
		proposedLandUse: string | null;
		existingLandUse: string | null;
		siteAddress: string;
		councilDistrict: string | null;
		applicationDate: string | null;
		statusDate: string | null;
		ownerName: string | null;
		caseManager: string | null;
		isResidentialImpact: boolean;
	}[];
	applications: {
		id: string;
		type: string;
		description: string;
		address: string;
		zip: string;
		applicant: string;
		contractor: string | null;
		value: string | null;
		appliedDate: string | null;
		status: string;
		permitClass: string | null;
	}[];
	lastUpdated: string;
}>;
export declare function addHomeowner(input: {
	hoaId: string;
	name: string;
	email: string;
	phone?: string;
	address: string;
	unit?: string;
	role?: string;
	monthlyDueCents?: number;
}): Promise<{
	id: string;
	email: string;
	phone: string | null;
	createdAt: Date;
	name: string;
	hoaId: string;
	address: string;
	unit: string | null;
	role: string;
	stripeCustomerId: string | null;
	moveInDate: Date | null;
	active: boolean;
}>;
export declare function getHomeowners(hoaId: string): Promise<({
	duesAccount: {
		id: string;
		createdAt: Date;
		homeownerId: string;
		balanceCents: number;
		monthlyDueCents: number;
		overdueMonths: number;
		lastPaymentAt: Date | null;
		autopayEnabled: boolean;
		stripePaymentMethodId: string | null;
		lastChargedAt: Date | null;
		nextDueDate: Date | null;
		aiAnalysis: string | null;
		aiAnalyzedAt: Date | null;
		updatedAt: Date;
	} | null;
	_count: {
		violations: number;
		workOrders: number;
	};
} & {
	id: string;
	email: string;
	phone: string | null;
	createdAt: Date;
	name: string;
	hoaId: string;
	address: string;
	unit: string | null;
	role: string;
	stripeCustomerId: string | null;
	moveInDate: Date | null;
	active: boolean;
})[]>;
export declare function getDuesAccount(homeownerId: string): Promise<({
	homeowner: {
		email: string;
		name: string;
		address: string;
	};
	transactions: {
		type: string;
		id: string;
		paidAt: Date | null;
		createdAt: Date;
		amountCents: number;
		description: string;
		status: string;
		dueDate: Date | null;
		stripePaymentIntentId: string | null;
		duesAccountId: string;
	}[];
} & {
	id: string;
	createdAt: Date;
	homeownerId: string;
	balanceCents: number;
	monthlyDueCents: number;
	overdueMonths: number;
	lastPaymentAt: Date | null;
	autopayEnabled: boolean;
	stripePaymentMethodId: string | null;
	lastChargedAt: Date | null;
	nextDueDate: Date | null;
	aiAnalysis: string | null;
	aiAnalyzedAt: Date | null;
	updatedAt: Date;
}) | null>;
export declare function chargeMonthlyDues(hoaId: string): Promise<{
	charged: number;
	results: {
		homeownerId: string;
		transactionId: string;
		amountCents: number;
	}[];
}>;
export declare function recordPayment(input: {
	duesAccountId: string;
	amountCents: number;
	description?: string;
	stripePaymentIntentId?: string;
}): Promise<{
	type: string;
	id: string;
	paidAt: Date | null;
	createdAt: Date;
	amountCents: number;
	description: string;
	status: string;
	dueDate: Date | null;
	stripePaymentIntentId: string | null;
	duesAccountId: string;
}>;
export declare function getFinancialSummary(hoaId: string): Promise<{
	totalOutstanding: number;
	delinquentCount: number;
	delinquentAmount: number;
	budgetedYTD: number;
	actualYTD: number;
	variance: number;
	homeownerCount: number;
}>;
export declare function addBudgetLine(input: {
	hoaId: string;
	year: number;
	month?: number;
	category: string;
	name: string;
	budgetedCents: number;
	notes?: string;
}): Promise<{
	id: string;
	category: string;
	createdAt: Date;
	name: string;
	hoaId: string;
	notes: string | null;
	month: number | null;
	year: number;
	budgetedCents: number;
	actualCents: number;
}>;
export declare function createViolation(input: {
	hoaId: string;
	homeownerId?: string;
	address: string;
	category: string;
	description: string;
	severity?: string;
	reportedBy?: string;
	photoUrls?: string[];
}): Promise<{
	id: string;
	category: string;
	createdAt: Date;
	hoaId: string;
	address: string;
	homeownerId: string | null;
	aiAnalysis: string | null;
	aiAnalyzedAt: Date | null;
	updatedAt: Date;
	description: string;
	severity: string;
	status: string;
	photoUrls: string | null;
	reportedBy: string | null;
	noticeCount: number;
	latestNoticeAt: Date | null;
	nextNoticeAt: Date | null;
	fineCents: number | null;
	resolvedAt: Date | null;
	notes: string | null;
}>;
export declare function getViolations(hoaId: string): Promise<({
	homeowner: {
		email: string;
		name: string;
	} | null;
	notices: {
		id: string;
		dueDate: Date;
		body: string;
		sentAt: Date;
		violationId: string;
		noticeNumber: number;
		sentTo: string;
		method: string;
		acknowledged: boolean;
		acknowledgedAt: Date | null;
	}[];
} & {
	id: string;
	category: string;
	createdAt: Date;
	hoaId: string;
	address: string;
	homeownerId: string | null;
	aiAnalysis: string | null;
	aiAnalyzedAt: Date | null;
	updatedAt: Date;
	description: string;
	severity: string;
	status: string;
	photoUrls: string | null;
	reportedBy: string | null;
	noticeCount: number;
	latestNoticeAt: Date | null;
	nextNoticeAt: Date | null;
	fineCents: number | null;
	resolvedAt: Date | null;
	notes: string | null;
})[]>;
export declare function sendViolationNotice(violationId: string): Promise<{
	notice: {
		id: string;
		dueDate: Date;
		body: string;
		sentAt: Date;
		violationId: string;
		noticeNumber: number;
		sentTo: string;
		method: string;
		acknowledged: boolean;
		acknowledgedAt: Date | null;
	};
	noticeNumber: number;
	fineCents: number;
}>;
export declare function resolveViolation(violationId: string, notes?: string): Promise<{
	id: string;
	category: string;
	createdAt: Date;
	hoaId: string;
	address: string;
	homeownerId: string | null;
	aiAnalysis: string | null;
	aiAnalyzedAt: Date | null;
	updatedAt: Date;
	description: string;
	severity: string;
	status: string;
	photoUrls: string | null;
	reportedBy: string | null;
	noticeCount: number;
	latestNoticeAt: Date | null;
	nextNoticeAt: Date | null;
	fineCents: number | null;
	resolvedAt: Date | null;
	notes: string | null;
}>;
export declare function submitARCRequest(input: {
	hoaId: string;
	homeownerId: string;
	address: string;
	projectType: string;
	description: string;
	estimatedCost?: number;
	startDate?: string;
	documentUrls?: string[];
}): Promise<{
	id: string;
	hoaId: string;
	address: string;
	homeownerId: string;
	aiAnalysis: string | null;
	aiAnalyzedAt: Date | null;
	updatedAt: Date;
	description: string;
	status: string;
	projectType: string;
	estimatedCost: number | null;
	startDate: Date | null;
	documentUrls: string | null;
	reviewDeadline: Date;
	reviewedBy: string | null;
	reviewNotes: string | null;
	conditions: string | null;
	submittedAt: Date;
	decidedAt: Date | null;
}>;
export declare function getARCRequests(hoaId: string): Promise<({
	homeowner: {
		email: string;
		name: string;
		address: string;
	};
} & {
	id: string;
	hoaId: string;
	address: string;
	homeownerId: string;
	aiAnalysis: string | null;
	aiAnalyzedAt: Date | null;
	updatedAt: Date;
	description: string;
	status: string;
	projectType: string;
	estimatedCost: number | null;
	startDate: Date | null;
	documentUrls: string | null;
	reviewDeadline: Date;
	reviewedBy: string | null;
	reviewNotes: string | null;
	conditions: string | null;
	submittedAt: Date;
	decidedAt: Date | null;
})[]>;
export declare function reviewARCRequest(input: {
	id: string;
	status: "approved" | "denied" | "revision_requested";
	reviewedBy: string;
	reviewNotes?: string;
	conditions?: string;
}): Promise<{
	id: string;
	hoaId: string;
	address: string;
	homeownerId: string;
	aiAnalysis: string | null;
	aiAnalyzedAt: Date | null;
	updatedAt: Date;
	description: string;
	status: string;
	projectType: string;
	estimatedCost: number | null;
	startDate: Date | null;
	documentUrls: string | null;
	reviewDeadline: Date;
	reviewedBy: string | null;
	reviewNotes: string | null;
	conditions: string | null;
	submittedAt: Date;
	decidedAt: Date | null;
}>;
export declare function createMeeting(input: {
	hoaId: string;
	title: string;
	type?: string;
	scheduledAt: string;
	location?: string;
	virtualLink?: string;
	agenda?: string;
	quorumRequired?: number;
}): Promise<{
	type: string;
	id: string;
	createdAt: Date;
	hoaId: string;
	aiAnalysis: string | null;
	aiAnalyzedAt: Date | null;
	updatedAt: Date;
	status: string;
	title: string;
	location: string | null;
	scheduledAt: Date;
	virtualLink: string | null;
	agenda: string | null;
	minutes: string | null;
	quorumRequired: number | null;
	quorumMet: boolean | null;
}>;
export declare function getMeetings(hoaId: string): Promise<({
	votes: {
		id: string;
		status: string;
		title: string;
	}[];
	agendaItems: {
		id: string;
		createdAt: Date;
		description: string | null;
		status: string;
		notes: string | null;
		title: string;
		meetingId: string;
		order: number;
		presenter: string | null;
		actionRequired: boolean;
		duration: number | null;
	}[];
} & {
	type: string;
	id: string;
	createdAt: Date;
	hoaId: string;
	aiAnalysis: string | null;
	aiAnalyzedAt: Date | null;
	updatedAt: Date;
	status: string;
	title: string;
	location: string | null;
	scheduledAt: Date;
	virtualLink: string | null;
	agenda: string | null;
	minutes: string | null;
	quorumRequired: number | null;
	quorumMet: boolean | null;
})[]>;
export declare function updateMeetingMinutes(input: {
	id: string;
	minutes: string;
	quorumMet?: boolean;
	status?: string;
}): Promise<{
	type: string;
	id: string;
	createdAt: Date;
	hoaId: string;
	aiAnalysis: string | null;
	aiAnalyzedAt: Date | null;
	updatedAt: Date;
	status: string;
	title: string;
	location: string | null;
	scheduledAt: Date;
	virtualLink: string | null;
	agenda: string | null;
	minutes: string | null;
	quorumRequired: number | null;
	quorumMet: boolean | null;
}>;
export declare function addAgendaItem(input: {
	meetingId: string;
	order: number;
	title: string;
	description?: string;
	presenter?: string;
	duration?: number;
}): Promise<{
	id: string;
	createdAt: Date;
	description: string | null;
	status: string;
	notes: string | null;
	title: string;
	meetingId: string;
	order: number;
	presenter: string | null;
	actionRequired: boolean;
	duration: number | null;
}>;
export declare function createVote(input: {
	hoaId: string;
	meetingId?: string;
	title: string;
	description?: string;
	type?: string;
	options: string[];
	allowMultiple?: boolean;
	requiresQuorum?: boolean;
	quorumCount?: number;
	closesAt: string;
}): Promise<{
	type: string;
	id: string;
	createdAt: Date;
	hoaId: string;
	aiAnalysis: string | null;
	aiAnalyzedAt: Date | null;
	description: string | null;
	status: string;
	title: string;
	meetingId: string | null;
	options: string;
	allowMultiple: boolean;
	requiresQuorum: boolean;
	quorumCount: number | null;
	opensAt: Date;
	closesAt: Date;
	resultSummary: string | null;
	certifiedAt: Date | null;
}>;
export declare function getVotes(hoaId: string): Promise<({
	meeting: {
		title: string;
		scheduledAt: Date;
	} | null;
	casts: {
		id: string;
		homeownerId: string;
		voteId: string;
		selection: string;
		castAt: Date;
	}[];
} & {
	type: string;
	id: string;
	createdAt: Date;
	hoaId: string;
	aiAnalysis: string | null;
	aiAnalyzedAt: Date | null;
	description: string | null;
	status: string;
	title: string;
	meetingId: string | null;
	options: string;
	allowMultiple: boolean;
	requiresQuorum: boolean;
	quorumCount: number | null;
	opensAt: Date;
	closesAt: Date;
	resultSummary: string | null;
	certifiedAt: Date | null;
})[]>;
export declare function castVote(input: {
	voteId: string;
	homeownerId: string;
	selection: string[];
}): Promise<{
	id: string;
	homeownerId: string;
	voteId: string;
	selection: string;
	castAt: Date;
}>;
export declare function getVoteResults(voteId: string): Promise<{
	voteId: string;
	title: string;
	totalCasts: number;
	quorumMet: boolean;
	tallies: Record<string, number>;
	status: string;
	closesAt: Date;
}>;
export declare function closeVote(voteId: string): Promise<{
	type: string;
	id: string;
	createdAt: Date;
	hoaId: string;
	aiAnalysis: string | null;
	aiAnalyzedAt: Date | null;
	description: string | null;
	status: string;
	title: string;
	meetingId: string | null;
	options: string;
	allowMultiple: boolean;
	requiresQuorum: boolean;
	quorumCount: number | null;
	opensAt: Date;
	closesAt: Date;
	resultSummary: string | null;
	certifiedAt: Date | null;
}>;
export declare function createWorkOrder(input: {
	hoaId: string;
	homeownerId?: string;
	title: string;
	description: string;
	category: string;
	location: string;
	priority?: string;
	estimatedCost?: number;
	dueDate?: string;
}): Promise<{
	id: string;
	category: string;
	createdAt: Date;
	hoaId: string;
	homeownerId: string | null;
	aiAnalysis: string | null;
	aiAnalyzedAt: Date | null;
	updatedAt: Date;
	description: string;
	status: string;
	photoUrls: string | null;
	notes: string | null;
	estimatedCost: number | null;
	title: string;
	area: string | null;
	location: string;
	priority: string;
	assignedTo: string | null;
	assignedAt: Date | null;
	actualCost: number | null;
	completionNotes: string | null;
	boardApproved: boolean;
	boardApprovedAt: Date | null;
	dueDate: Date | null;
	completedAt: Date | null;
}>;
export declare function getWorkOrders(hoaId: string): Promise<({
	homeowner: {
		name: string;
		address: string;
	} | null;
} & {
	id: string;
	category: string;
	createdAt: Date;
	hoaId: string;
	homeownerId: string | null;
	aiAnalysis: string | null;
	aiAnalyzedAt: Date | null;
	updatedAt: Date;
	description: string;
	status: string;
	photoUrls: string | null;
	notes: string | null;
	estimatedCost: number | null;
	title: string;
	area: string | null;
	location: string;
	priority: string;
	assignedTo: string | null;
	assignedAt: Date | null;
	actualCost: number | null;
	completionNotes: string | null;
	boardApproved: boolean;
	boardApprovedAt: Date | null;
	dueDate: Date | null;
	completedAt: Date | null;
})[]>;
export declare function updateWorkOrder(input: {
	id: string;
	status?: string;
	assignedTo?: string;
	actualCost?: number;
	completionNotes?: string;
	boardApproved?: boolean;
}): Promise<{
	id: string;
	category: string;
	createdAt: Date;
	hoaId: string;
	homeownerId: string | null;
	aiAnalysis: string | null;
	aiAnalyzedAt: Date | null;
	updatedAt: Date;
	description: string;
	status: string;
	photoUrls: string | null;
	notes: string | null;
	estimatedCost: number | null;
	title: string;
	area: string | null;
	location: string;
	priority: string;
	assignedTo: string | null;
	assignedAt: Date | null;
	actualCost: number | null;
	completionNotes: string | null;
	boardApproved: boolean;
	boardApprovedAt: Date | null;
	dueDate: Date | null;
	completedAt: Date | null;
}>;
export declare function createAmenity(input: {
	hoaId: string;
	name: string;
	description?: string;
	capacity?: number;
	rules?: string;
	depositCents?: number;
	openTime?: string;
	closeTime?: string;
	advanceBookingDays?: number;
}): Promise<{
	id: string;
	createdAt: Date;
	name: string;
	hoaId: string;
	active: boolean;
	description: string | null;
	capacity: number | null;
	rules: string | null;
	depositCents: number | null;
	openTime: string | null;
	closeTime: string | null;
	advanceBookingDays: number | null;
}>;
export declare function getAmenities(hoaId: string): Promise<({
	reservations: ({
		homeowner: {
			name: string;
		};
	} & {
		id: string;
		createdAt: Date;
		homeownerId: string;
		aiAnalysis: string | null;
		aiAnalyzedAt: Date | null;
		updatedAt: Date;
		status: string;
		notes: string | null;
		amenityId: string;
		date: string;
		startTime: string;
		endTime: string;
		partySize: number | null;
		guestCount: number | null;
		depositPaid: boolean;
		depositRefunded: boolean;
	})[];
} & {
	id: string;
	createdAt: Date;
	name: string;
	hoaId: string;
	active: boolean;
	description: string | null;
	capacity: number | null;
	rules: string | null;
	depositCents: number | null;
	openTime: string | null;
	closeTime: string | null;
	advanceBookingDays: number | null;
})[]>;
export declare function createReservation(input: {
	amenityId: string;
	homeownerId: string;
	date: string;
	startTime: string;
	endTime: string;
	guestCount?: number;
	notes?: string;
}): Promise<{
	id: string;
	createdAt: Date;
	homeownerId: string;
	aiAnalysis: string | null;
	aiAnalyzedAt: Date | null;
	updatedAt: Date;
	status: string;
	notes: string | null;
	amenityId: string;
	date: string;
	startTime: string;
	endTime: string;
	partySize: number | null;
	guestCount: number | null;
	depositPaid: boolean;
	depositRefunded: boolean;
}>;
export declare function cancelReservation(id: string): Promise<{
	id: string;
	createdAt: Date;
	homeownerId: string;
	aiAnalysis: string | null;
	aiAnalyzedAt: Date | null;
	updatedAt: Date;
	status: string;
	notes: string | null;
	amenityId: string;
	date: string;
	startTime: string;
	endTime: string;
	partySize: number | null;
	guestCount: number | null;
	depositPaid: boolean;
	depositRefunded: boolean;
}>;
export declare function createAnnouncement(input: {
	hoaId: string;
	title: string;
	body: string;
	category?: string;
	pinned?: boolean;
	authorName: string;
	expiresAt?: string;
}): Promise<{
	id: string;
	category: string;
	createdAt: Date;
	hoaId: string;
	aiAnalysis: string | null;
	aiAnalyzedAt: Date | null;
	title: string;
	body: string;
	pinned: boolean;
	sentEmail: boolean;
	sentAt: Date | null;
	authorName: string;
	expiresAt: Date | null;
}>;
export declare function getAnnouncements(hoaId: string): Promise<{
	id: string;
	category: string;
	createdAt: Date;
	hoaId: string;
	aiAnalysis: string | null;
	aiAnalyzedAt: Date | null;
	title: string;
	body: string;
	pinned: boolean;
	sentEmail: boolean;
	sentAt: Date | null;
	authorName: string;
	expiresAt: Date | null;
}[]>;
export declare function sendMessage(input: {
	homeownerId: string;
	subject: string;
	body: string;
	direction: "inbound" | "outbound";
	category?: string;
	referenceId?: string;
	referenceType?: string;
}): Promise<{
	id: string;
	category: string;
	createdAt: Date;
	homeownerId: string;
	updatedAt: Date;
	status: string;
	body: string;
	subject: string;
	direction: string;
	referenceId: string | null;
	referenceType: string | null;
}>;
export declare function getMessages(homeownerId: string): Promise<({
	homeowner: {
		name: string;
		address: string;
	};
} & {
	id: string;
	category: string;
	createdAt: Date;
	homeownerId: string;
	updatedAt: Date;
	status: string;
	body: string;
	subject: string;
	direction: string;
	referenceId: string | null;
	referenceType: string | null;
})[]>;
export declare function getHOAMessages(hoaId: string): Promise<({
	homeowner: {
		name: string;
		address: string;
	};
} & {
	id: string;
	category: string;
	createdAt: Date;
	homeownerId: string;
	updatedAt: Date;
	status: string;
	body: string;
	subject: string;
	direction: string;
	referenceId: string | null;
	referenceType: string | null;
})[]>;
export declare function sendHOAWelcomeEmail(hoaId: string): Promise<{
	sent: boolean;
}>;
export declare function sendViolationNoticeEmail(violationId: string): Promise<{
	sent: boolean;
}>;
export declare function sendARCDecisionEmail(arcId: string): Promise<{
	sent: boolean;
}>;
export declare function sendContractorWelcomeEmail(contractorId: string): Promise<{
	sent: boolean;
}>;
export declare function stripeWebhook(input: {
	body: string;
	headers: Record<string, string | string[]>;
}): Promise<{
	received: boolean;
}>;
export declare function bulkImportHomeowners(input: {
	hoaId: string;
	csv: string;
}): Promise<{
	total: number;
	created: number;
	skipped: number;
	results: {
		name: string;
		status: "created" | "skipped";
		reason?: string;
	}[];
}>;
export declare function getGatePassMetrics(): Promise<{
	hoas: {
		total: number;
		paid: number;
	};
	homeowners: number;
	units: number;
	arr: number;
	violations: {
		open: number;
	};
	workOrders: {
		open: number;
	};
	arc: {
		pending: number;
	};
	contractors: {
		total: number;
		paid: number;
		spotsLeft: number;
	};
}>;
export type TransitionStatus = "identified" | "contacted" | "meeting" | "exit_pack_sent" | "pilot_scoped" | "won" | "lost" | "parked";
export type MoatSignalCategory = "board_objection" | "contract_fact" | "pmc_failure" | "switching_trigger" | "compliance_risk" | "proof_artifact" | "case_study_metric";
export declare function createTransitionCase(input: {
	hoaId: string;
	currentPmc: string;
	priorPmc?: string;
	sourceSignal: string;
	sourceUrl?: string;
	signalSummary: string;
	complaintThemes: string[];
	contractStatus?: string;
	renewalDate?: string;
	noticeWindowDays?: number;
	terminationFeeCents?: number;
	buyoutOfferedCents?: number;
	boardFear?: string;
	decidingProof?: string;
	counterMove?: string;
	nextStep?: string;
	status?: TransitionStatus;
}): Promise<{
	id: string;
	createdAt: Date;
	hoaId: string;
	updatedAt: Date;
	status: string;
	currentPmc: string;
	priorPmc: string | null;
	sourceSignal: string;
	sourceUrl: string | null;
	signalSummary: string;
	complaintThemes: string;
	contractStatus: string;
	renewalDate: Date | null;
	noticeWindowDays: number | null;
	terminationFeeCents: number | null;
	buyoutOfferedCents: number | null;
	boardFear: string | null;
	decidingProof: string | null;
	counterMove: string | null;
	nextStep: string | null;
	transitionScore: number;
	replicabilityScore: number;
	dataCompleteness: number;
}>;
export declare function updateTransitionCase(input: {
	id: string;
	contractStatus?: string;
	renewalDate?: string;
	noticeWindowDays?: number;
	terminationFeeCents?: number;
	buyoutOfferedCents?: number;
	boardFear?: string;
	decidingProof?: string;
	counterMove?: string;
	nextStep?: string;
	status?: TransitionStatus;
}): Promise<{
	id: string;
	createdAt: Date;
	hoaId: string;
	updatedAt: Date;
	status: string;
	currentPmc: string;
	priorPmc: string | null;
	sourceSignal: string;
	sourceUrl: string | null;
	signalSummary: string;
	complaintThemes: string;
	contractStatus: string;
	renewalDate: Date | null;
	noticeWindowDays: number | null;
	terminationFeeCents: number | null;
	buyoutOfferedCents: number | null;
	boardFear: string | null;
	decidingProof: string | null;
	counterMove: string | null;
	nextStep: string | null;
	transitionScore: number;
	replicabilityScore: number;
	dataCompleteness: number;
}>;
export declare function addBoardStakeholder(input: {
	hoaId: string;
	transitionCaseId?: string;
	name: string;
	role: string;
	contact?: string;
	stance?: "champion" | "supporter" | "neutral" | "blocker" | "unknown";
	primaryConcern?: string;
	persuasionAngle?: string;
	notes?: string;
}): Promise<{
	id: string;
	createdAt: Date;
	name: string;
	hoaId: string;
	role: string;
	updatedAt: Date;
	notes: string | null;
	transitionCaseId: string | null;
	contact: string | null;
	stance: string;
	primaryConcern: string | null;
	persuasionAngle: string | null;
	lastInteractionAt: Date | null;
}>;
export declare function addMoatSignal(input: {
	hoaId: string;
	transitionCaseId?: string;
	category: MoatSignalCategory;
	label: string;
	evidence: string;
	source: string;
	confidence?: "low" | "medium" | "high" | "verified";
	isPubliclyReplicable?: boolean;
	moatWeight?: number;
	capturedBy?: string;
}): Promise<{
	id: string;
	category: string;
	createdAt: Date;
	hoaId: string;
	confidence: string;
	transitionCaseId: string | null;
	label: string;
	evidence: string;
	source: string;
	isPubliclyReplicable: boolean;
	moatWeight: number;
	capturedBy: string;
}>;
export declare function getTransitionMoat(hoaId: string): Promise<{
	summary: {
		transitionCases: number;
		boardStakeholders: number;
		moatSignals: number;
		privateSignals: number;
		weightedMoat: number;
		averageReplicability: number;
		complianceEvents: number;
		legalComplianceEvents: number;
		investorLine: string;
	};
	cases: {
		stakeholders: {
			id: string;
			hoaId: string;
			transitionCaseId: string;
			name: string;
			role: string;
			contact: string;
			stance: string;
			primaryConcern: string;
			persuasionAngle: string;
			lastInteractionAt: string;
			notes: string;
			createdAt: string;
			updatedAt: string;
		}[];
		moatSignals: {
			id: string;
			hoaId: string;
			transitionCaseId: string;
			category: string;
			label: string;
			evidence: string;
			source: string;
			confidence: string;
			isPubliclyReplicable: boolean;
			moatWeight: number;
			capturedBy: string;
			createdAt: string;
		}[];
		id: string;
		hoaId: string;
		currentPmc: string;
		priorPmc: null;
		sourceSignal: string;
		sourceUrl: string;
		signalSummary: string;
		complaintThemes: string[];
		contractStatus: string;
		renewalDate: string;
		noticeWindowDays: number;
		terminationFeeCents: number;
		buyoutOfferedCents: null;
		boardFear: string;
		decidingProof: string;
		counterMove: string;
		nextStep: string;
		status: string;
		transitionScore: number;
		replicabilityScore: number;
		dataCompleteness: number;
		createdAt: string;
		updatedAt: string;
	}[];
	stakeholders: {
		id: string;
		hoaId: string;
		transitionCaseId: string;
		name: string;
		role: string;
		contact: string;
		stance: string;
		primaryConcern: string;
		persuasionAngle: string;
		lastInteractionAt: string;
		notes: string;
		createdAt: string;
		updatedAt: string;
	}[];
	signals: {
		id: string;
		hoaId: string;
		transitionCaseId: string;
		category: string;
		label: string;
		evidence: string;
		source: string;
		confidence: string;
		isPubliclyReplicable: boolean;
		moatWeight: number;
		capturedBy: string;
		createdAt: string;
	}[];
} | {
	summary: {
		transitionCases: number;
		boardStakeholders: number;
		moatSignals: number;
		privateSignals: number;
		weightedMoat: number;
		averageReplicability: number;
		complianceEvents: number;
		legalComplianceEvents: number;
		investorLine: string;
	};
	cases: {
		complaintThemes: string[];
		moatSignals: {
			id: string;
			category: string;
			createdAt: Date;
			hoaId: string;
			confidence: string;
			transitionCaseId: string | null;
			label: string;
			evidence: string;
			source: string;
			isPubliclyReplicable: boolean;
			moatWeight: number;
			capturedBy: string;
		}[];
		stakeholders: {
			id: string;
			createdAt: Date;
			name: string;
			hoaId: string;
			role: string;
			updatedAt: Date;
			notes: string | null;
			transitionCaseId: string | null;
			contact: string | null;
			stance: string;
			primaryConcern: string | null;
			persuasionAngle: string | null;
			lastInteractionAt: Date | null;
		}[];
		id: string;
		createdAt: Date;
		hoaId: string;
		updatedAt: Date;
		status: string;
		currentPmc: string;
		priorPmc: string | null;
		sourceSignal: string;
		sourceUrl: string | null;
		signalSummary: string;
		contractStatus: string;
		renewalDate: Date | null;
		noticeWindowDays: number | null;
		terminationFeeCents: number | null;
		buyoutOfferedCents: number | null;
		boardFear: string | null;
		decidingProof: string | null;
		counterMove: string | null;
		nextStep: string | null;
		transitionScore: number;
		replicabilityScore: number;
		dataCompleteness: number;
	}[];
	stakeholders: {
		id: string;
		createdAt: Date;
		name: string;
		hoaId: string;
		role: string;
		updatedAt: Date;
		notes: string | null;
		transitionCaseId: string | null;
		contact: string | null;
		stance: string;
		primaryConcern: string | null;
		persuasionAngle: string | null;
		lastInteractionAt: Date | null;
	}[];
	signals: {
		id: string;
		category: string;
		createdAt: Date;
		hoaId: string;
		confidence: string;
		transitionCaseId: string | null;
		label: string;
		evidence: string;
		source: string;
		isPubliclyReplicable: boolean;
		moatWeight: number;
		capturedBy: string;
	}[];
}>;
export declare function exportPilotProofPack(input: {
	hoaId: string;
	transitionCaseId?: string;
	requestedBy: string;
}): Promise<{
	generatedAt: string;
	requestedBy: string;
	demo: boolean;
	title: string;
	positioning: string;
	moatThesis: {
		publicData: string;
		proprietaryData: string;
		hardLine: string;
	};
	community: {
		id: string;
		name: string;
		community: string;
		units: number;
		plan: string;
	};
	selectedCase: {
		stakeholders: {
			id: string;
			hoaId: string;
			transitionCaseId: string;
			name: string;
			role: string;
			contact: string;
			stance: string;
			primaryConcern: string;
			persuasionAngle: string;
			lastInteractionAt: string;
			notes: string;
			createdAt: string;
			updatedAt: string;
		}[];
		moatSignals: {
			id: string;
			hoaId: string;
			transitionCaseId: string;
			category: string;
			label: string;
			evidence: string;
			source: string;
			confidence: string;
			isPubliclyReplicable: boolean;
			moatWeight: number;
			capturedBy: string;
			createdAt: string;
		}[];
		id: string;
		hoaId: string;
		currentPmc: string;
		priorPmc: null;
		sourceSignal: string;
		sourceUrl: string;
		signalSummary: string;
		complaintThemes: string[];
		contractStatus: string;
		renewalDate: string;
		noticeWindowDays: number;
		terminationFeeCents: number;
		buyoutOfferedCents: null;
		boardFear: string;
		decidingProof: string;
		counterMove: string;
		nextStep: string;
		status: string;
		transitionScore: number;
		replicabilityScore: number;
		dataCompleteness: number;
		createdAt: string;
		updatedAt: string;
	} | undefined;
	moatSummary: {
		transitionCases: number;
		boardStakeholders: number;
		moatSignals: number;
		privateSignals: number;
		weightedMoat: number;
		averageReplicability: number;
		complianceEvents: number;
		legalComplianceEvents: number;
		investorLine: string;
	};
	topSignals: {
		id: string;
		hoaId: string;
		transitionCaseId: string;
		category: string;
		label: string;
		evidence: string;
		source: string;
		confidence: string;
		isPubliclyReplicable: boolean;
		moatWeight: number;
		capturedBy: string;
		createdAt: string;
	}[];
	boardMap: {
		id: string;
		hoaId: string;
		transitionCaseId: string;
		name: string;
		role: string;
		contact: string;
		stance: string;
		primaryConcern: string;
		persuasionAngle: string;
		lastInteractionAt: string;
		notes: string;
		createdAt: string;
		updatedAt: string;
	}[];
	complianceSummary: {
		totalEvents: number;
		legalEvents: number;
		moduleBreakdown: {
			transition: number;
			boardroom: number;
			workorder: number;
		};
	};
	legalHighlights: {
		module: string;
		eventType: string;
		summary: string;
		actor: string;
		legalCategory: string;
	}[];
	firstPilotProofChecklist: string[];
} | {
	generatedAt: string;
	requestedBy: string;
	title: string;
	positioning: string;
	moatThesis: {
		publicData: string;
		proprietaryData: string;
		hardLine: string;
	};
	community: {
		id: string;
		name: string;
		community: string;
		units: number;
		plan: string;
	};
	selectedCase: {
		stakeholders: {
			id: string;
			hoaId: string;
			transitionCaseId: string;
			name: string;
			role: string;
			contact: string;
			stance: string;
			primaryConcern: string;
			persuasionAngle: string;
			lastInteractionAt: string;
			notes: string;
			createdAt: string;
			updatedAt: string;
		}[];
		moatSignals: {
			id: string;
			hoaId: string;
			transitionCaseId: string;
			category: string;
			label: string;
			evidence: string;
			source: string;
			confidence: string;
			isPubliclyReplicable: boolean;
			moatWeight: number;
			capturedBy: string;
			createdAt: string;
		}[];
		id: string;
		hoaId: string;
		currentPmc: string;
		priorPmc: null;
		sourceSignal: string;
		sourceUrl: string;
		signalSummary: string;
		complaintThemes: string[];
		contractStatus: string;
		renewalDate: string;
		noticeWindowDays: number;
		terminationFeeCents: number;
		buyoutOfferedCents: null;
		boardFear: string;
		decidingProof: string;
		counterMove: string;
		nextStep: string;
		status: string;
		transitionScore: number;
		replicabilityScore: number;
		dataCompleteness: number;
		createdAt: string;
		updatedAt: string;
	} | {
		complaintThemes: string[];
		moatSignals: {
			id: string;
			category: string;
			createdAt: Date;
			hoaId: string;
			confidence: string;
			transitionCaseId: string | null;
			label: string;
			evidence: string;
			source: string;
			isPubliclyReplicable: boolean;
			moatWeight: number;
			capturedBy: string;
		}[];
		stakeholders: {
			id: string;
			createdAt: Date;
			name: string;
			hoaId: string;
			role: string;
			updatedAt: Date;
			notes: string | null;
			transitionCaseId: string | null;
			contact: string | null;
			stance: string;
			primaryConcern: string | null;
			persuasionAngle: string | null;
			lastInteractionAt: Date | null;
		}[];
		id: string;
		createdAt: Date;
		hoaId: string;
		updatedAt: Date;
		status: string;
		currentPmc: string;
		priorPmc: string | null;
		sourceSignal: string;
		sourceUrl: string | null;
		signalSummary: string;
		contractStatus: string;
		renewalDate: Date | null;
		noticeWindowDays: number | null;
		terminationFeeCents: number | null;
		buyoutOfferedCents: number | null;
		boardFear: string | null;
		decidingProof: string | null;
		counterMove: string | null;
		nextStep: string | null;
		transitionScore: number;
		replicabilityScore: number;
		dataCompleteness: number;
	} | undefined;
	moatSummary: {
		transitionCases: number;
		boardStakeholders: number;
		moatSignals: number;
		privateSignals: number;
		weightedMoat: number;
		averageReplicability: number;
		complianceEvents: number;
		legalComplianceEvents: number;
		investorLine: string;
	} | {
		transitionCases: number;
		boardStakeholders: number;
		moatSignals: number;
		privateSignals: number;
		weightedMoat: number;
		averageReplicability: number;
		complianceEvents: number;
		legalComplianceEvents: number;
		investorLine: string;
	};
	topSignals: {
		id: string;
		hoaId: string;
		transitionCaseId: string;
		category: string;
		label: string;
		evidence: string;
		source: string;
		confidence: string;
		isPubliclyReplicable: boolean;
		moatWeight: number;
		capturedBy: string;
		createdAt: string;
	}[] | {
		id: string;
		category: string;
		createdAt: Date;
		hoaId: string;
		confidence: string;
		transitionCaseId: string | null;
		label: string;
		evidence: string;
		source: string;
		isPubliclyReplicable: boolean;
		moatWeight: number;
		capturedBy: string;
	}[];
	boardMap: {
		id: string;
		hoaId: string;
		transitionCaseId: string;
		name: string;
		role: string;
		contact: string;
		stance: string;
		primaryConcern: string;
		persuasionAngle: string;
		lastInteractionAt: string;
		notes: string;
		createdAt: string;
		updatedAt: string;
	}[] | {
		id: string;
		createdAt: Date;
		name: string;
		hoaId: string;
		role: string;
		updatedAt: Date;
		notes: string | null;
		transitionCaseId: string | null;
		contact: string | null;
		stance: string;
		primaryConcern: string | null;
		persuasionAngle: string | null;
		lastInteractionAt: Date | null;
	}[];
	complianceSummary: {
		totalEvents: number;
		legalEvents: number;
		moduleBreakdown: Record<string, number>;
	};
	legalHighlights: {
		date: Date;
		module: string;
		eventType: string;
		summary: string;
		actor: string;
		legalCategory: string | null;
	}[];
	firstPilotProofChecklist: string[];
	demo?: undefined;
}>;
export declare function getOSDashboard(hoaId: string): Promise<{
	hoa: ({
		homeowners: {
			id: string;
		}[];
	} & {
		id: string;
		contactName: string;
		zip: string;
		city: string;
		state: string;
		stripeSessionId: string | null;
		paid: boolean;
		paidAt: Date | null;
		createdAt: Date;
		name: string;
		community: string;
		units: number;
		contactEmail: string;
		contactPhone: string | null;
		amountCents: number | null;
		plan: string;
		pricePerUnit: number;
		onboardedAt: Date | null;
	}) | null;
	stats: {
		homeowners: number;
		openViolations: number;
		openWorkOrders: number;
		pendingARC: number;
		openVotes: number;
	};
	nextMeeting: {
		type: string;
		id: string;
		createdAt: Date;
		hoaId: string;
		aiAnalysis: string | null;
		aiAnalyzedAt: Date | null;
		updatedAt: Date;
		status: string;
		title: string;
		location: string | null;
		scheduledAt: Date;
		virtualLink: string | null;
		agenda: string | null;
		minutes: string | null;
		quorumRequired: number | null;
		quorumMet: boolean | null;
	} | null;
	financial: {
		totalOutstanding: number;
		delinquentCount: number;
		delinquentAmount: number;
		budgetedYTD: number;
		actualYTD: number;
		variance: number;
		homeownerCount: number;
	};
}>;
export declare function runContractorScreening(contractorId: string): Promise<{
	jobId: number;
}>;
export declare function runDelinquencyAnalysis(input: {
	hoaId: string;
	homeownerId: string;
}): Promise<{
	jobId: number;
}>;
export declare function runViolationClassification(violationId: string): Promise<{
	jobId: number;
}>;
export declare function runARCReview(arcId: string): Promise<{
	jobId: number;
}>;
export declare function runWorkOrderRouting(workOrderId: string): Promise<{
	jobId: number;
}>;
export declare function runAgendaGeneration(meetingId: string): Promise<{
	jobId: number;
}>;
export declare function runVoteSummary(voteId: string): Promise<{
	jobId: number;
}>;
export declare function runReservationAnalysis(reservationId: string): Promise<{
	jobId: number;
}>;
export declare function runAnnouncementDraft(announcementId: string): Promise<{
	jobId: number;
}>;
export declare function getAgentJobStatus(jobId: number): Promise<{
	status: string;
	jobId: number;
	error?: undefined;
} | {
	status: string;
	jobId: number;
	error: string | undefined;
}>;
export declare function getAIAnalysis(input: {
	type: "violation" | "arc" | "workorder" | "meeting" | "vote" | "reservation" | "announcement" | "dues" | "contractor";
	id: string;
}): Promise<Record<string, unknown> | null>;
export declare function deleteHOA(hoaId: string): Promise<{
	deleted: boolean;
	community?: undefined;
} | {
	deleted: boolean;
	community: string;
}>;
export declare function seedDemoData(): Promise<{
	hoaId: string;
	community: string;
	stats: {
		homeowners: number;
		violations: number;
		arcRequests: number;
		workOrders: number;
		votes: number;
		amenities: number;
		reservations: number;
		announcements: number;
	};
}>;
/**
 * Internal utility — called by other procedures after the triggering DB write.
 * Fire-and-forget: never throws, never blocks the parent operation.
 */
export declare function logComplianceEvent(input: {
	hoaId: string;
	module: "core" | "payos" | "finebot" | "arc" | "workorder" | "boardroom" | "votebox" | "amenity" | "commhub" | "transition" | "marketplace";
	eventType: string;
	actorType: "board" | "homeowner" | "system" | "admin";
	actorId?: string;
	actorName: string;
	targetType?: string;
	targetId?: string;
	targetLabel?: string;
	summary: string;
	detail?: string;
	dataSnapshot?: Record<string, unknown>;
	legalFlag?: boolean;
	legalCategory?: "liability" | "financial" | "governance" | "enforcement" | "contract";
	documentHash?: string;
	documentUrl?: string;
}): Promise<void>;
export declare function getComplianceTimeline(input: {
	hoaId: string;
	page?: number;
	pageSize?: number;
	module?: string;
	legalOnly?: boolean;
	actorType?: string;
	targetId?: string;
	search?: string;
	dateFrom?: string;
	dateTo?: string;
}): Promise<{
	events: {
		id: string;
		createdAt: Date;
		hoaId: string;
		summary: string;
		legalFlag: boolean;
		module: string;
		eventType: string;
		actorType: string;
		actorId: string | null;
		actorName: string;
		targetType: string | null;
		targetId: string | null;
		targetLabel: string | null;
		detail: string | null;
		dataSnapshot: string | null;
		legalCategory: string | null;
		documentHash: string | null;
		documentUrl: string | null;
		ipAddress: string | null;
		userAgent: string | null;
	}[];
	total: number;
	page: number;
	pageSize: number;
	totalPages: number;
	legalCount: number;
}>;
export declare function exportCompliancePack(input: {
	hoaId: string;
	dateFrom: string;
	dateTo: string;
	purpose?: string;
	requestedBy: string;
}): Promise<{
	exportMeta: {
		generatedAt: string;
		requestedBy: string;
		purpose: string;
		hoaId: string;
		hoaName: string;
		community: string;
		dateRangeStart: string;
		dateRangeEnd: string;
	};
	summary: {
		totalEvents: number;
		legalEvents: number;
		moduleBreakdown: Record<string, number>;
	};
	legalHighlights: {
		date: Date;
		module: string;
		eventType: string;
		summary: string;
		actor: string;
		legalCategory: string | null;
	}[];
	fullTimeline: {
		id: string;
		date: Date;
		module: string;
		eventType: string;
		summary: string;
		detail: string | null;
		actor: string;
		target: string | null;
		legalFlag: boolean;
		legalCategory: string | null;
	}[];
}>;

export {};
